[project]
name = "mesay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
mesay = "mesay:main" # Replace "mesay" with the name you want for the executable

